### PR TITLE
ENG-1265: Fix build with -std=c++20

### PR DESCRIPTION
**Pull request by damien-projectx**

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/148/)
* Linux aarch64Build Status
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/76/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/140/)

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
The changes look good to me, but before merging we should [please the linter](http://jenkins.eprosima.com:8080/job/fastcdr_github_uncrustify/120/testReport/junit/build/uncrustify_results/include_fastcdr_Cdr_h/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/149/)
* Linux aarch64Build Status
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/77/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/141/)

**Comment by MiguelCompany** [comment]
Closing in favor of #138

**Pull request closed without merging**
