### PR TITLE
[15485] Fix SerializeArray error when swaping the bytes

### PR DESCRIPTION
**Pull request by wjswjq**
In SerializeArray Function, the '&' operator was used to a pointer.

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/124/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux%20aarch64/78/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/68/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/124/)

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
@wjswjq Thank you very much for your contribution!

The changes look good to me, but it would be great to extend the tests so they use both endianness kinds.

Updating the one [here](https://github.com/eProsima/Fast-CDR/blob/fe7f739552e114ea99584eaf5003ed8285d0c655/test/SimpleTest.cpp#L235) would be enough.

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux/125/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Linux%20aarch64/79/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Mac/69/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastCDR%20Manual%20Windows/125/)

**Comment by wjswjq** [comment]
@MiguelCompany Thanks for your advice!
I've submitted two commits accordingly.

**Review by MiguelCompany — APPROVED** [review]
LGTM!

**Comment by MiguelCompany** [comment]
@wjswjq Thanks for your contribution!

**Pull request merged**
